# Generated by Django 3.0.4 on 2020-03-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default=[], upload_to='avatars', verbose_name='avatar'),
        ),
    ]
