# Generated by Django 3.0.4 on 2020-03-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default='', upload_to='avatars', verbose_name='avatar'),
        ),
    ]
