# Generated by Django 3.0.4 on 2020-03-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200331_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
