# Generated by Django 3.0.5 on 2020-04-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_myuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
    ]
